# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Oliver's Tech Blog
email: oliver.savio@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Trying to change the world one line of code at a time.
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "oliver.savio@gmail.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  oliversavio

# Build settings
markdown: kramdown

#theme: jekyll-theme-cayman
remote_theme: pmarsceill/just-the-docs